name: qr_event_management
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  ai_barcode_scanner: ^7.0.0
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.4
  custom_numeric_pad: ^0.0.5
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_slidable: ^4.0.1
  gap: ^3.0.1
  get_it: ^8.0.3
  http: ^1.4.0
  iconify_flutter: ^0.0.7
  internet_connection_checker_plus: ^2.7.2
  intl: ^0.20.2
  lottie: ^3.3.1
  package_info_plus: ^8.3.0
  percent_indicator: ^4.2.5
  pinput: ^5.0.1
  provider: ^6.1.5
  pull_to_refresh_flutter3: ^2.0.2
  qr_code_scanner_plus: ^2.0.10+1
  shared_preferences: ^2.5.3
  toastification: ^3.0.3
  zoom_tap_animation: ^1.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo/cyberlabs.png
    - assets/lottie/wave_loading_nabildzr.json
    - assets/lottie/change_password_nabildzr.json
    - assets/lottie/success_nabildzr.json
    - assets/lottie/failed_nabildzr.json
